# -*- coding: utf-8 -*-
"""Evaluate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T9YpzaskKSAPKu0hpIzRuZbrXznKTBFm
"""

#Input dimensions and outout dimensions are the same as X
class Evaluate:
  def __init__(self, data):
    self.data = data
  def cross_entropy(self):
    self.data = -np.log(self.data)
